version: 2
updates:
  # Your existing configuration for the first package ecosystem
  - package-ecosystem: "" # Fill with your current ecosystem, e.g., "npm"
    directory: "/" # Assuming the root directory for manifest
    schedule:
      interval: "weekly" # Current update interval

  # Example addition: Configuration for a second package ecosystem
  - package-ecosystem: "maven" # Example for Java projects
    directory: "/backend" # Specify the directory if it's different
    schedule:
      interval: "monthly" # Maybe you prefer monthly updates for this ecosystem
    assignees: 
      - "team-java" # Automatically assign pull requests to a team or user
    labels:
      - "dependencies" # Automatically add labels to the pull requests
      - "java" # Example of a custom label
    milestone: 1 # Automatically set a milestone for the pull requests
    ignore:
      - dependency-name: "certain-dependency"
        versions: ["1.0.0"] # Ignore specific versions

  # Adding more ecosystems or additional settings follows the same pattern
