name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Login to ACR
      run: az acr login --name srikali2009

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: srikali2009.azurecr.io/myapp:${{ github.sha }}

    - name: Set Azure Web App settings
      run: |
        JSON=`cat test_appsettings.json`
        GRANT_TYPE=`echo $JSON | jq .GRANT_TYPE -r`
        TOKEN_URL=`echo $JSON | jq .TOKEN_URL -r`
        ORDER_SEARCH=`echo $JSON | jq .ORDER_SEARCH -r`
        az webapp config appsettings set --name srikali2009 --resource-group srikali2009 --settings GRANT_TYPE=$GRANT_TYPE TOKEN_URL=$TOKEN_URL ORDER_SEARCH=$ORDER_SEARCH
  
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: srikali2009
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        images: srikali2009.azurecr.io/myapp:${{ github.sha }}
