name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Login to ACR
      run: az acr login --name srikali2009

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: srikali2009.azurecr.io/myapp:${{ github.sha }}

    - name: Install Azure CLI App Configuration extension
      run: az extension add -n appconfig

    - name: Import test_appsettings.json to Azure App Configuration
      run: az appconfig kv import --name ${{ secrets.CONFIGURATION_STORE_NAME }} --format json --depth 2 --separator . --input ./test_appsettings.json --connection-string ${{ secrets.APP_CONFIGURATION_ACCESS_KEY }}

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        images: srikali2009.azurecr.io/myapp:${{ github.sha }}
