name: CI

on:
  push:
    branches:
      - main
      - Release-1.0
  pull_request:
    branches:
      - main
      - Release-1.0

jobs:
  build:
    if: github.ref == 'refs/heads/main'
    - name: Print Github Ref
      run: echo ${{ github.ref }}
    runs-on: ubuntu-latest
    environment: 
      name: 'Test'
    steps:
    - uses: actions/checkout@v2
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Login to ACR
      run: az acr login --name srikali2009
    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: srikali2009.azurecr.io/myapp:${{ github.sha }}
    - name: Validate JSON
      run: jq . < test_appsettings.json
    - name: Set Azure Web App settings
      run: |
        JSON=`cat test_appsettings.json`
        for key in $(jq -r 'keys[]' <<< "$JSON"); do
            value=$(jq -r --arg key "$key" '.[$key]' <<< "$JSON")
            az webapp config appsettings set --name srikali2009 --resource-group srikali2009 --settings $key=$value
        done
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        images: srikali2009.azurecr.io/myapp:${{ github.sha }}

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.3.0
      with:
        node-version: '14'
    - name: Install dependencies
      run: npm ci
    - name: Run Mocha tests
      run: npm run test:mocha 

  deploy_to_stage:
    needs: [build, test]
    if: github.ref == 'refs/heads/Release-1.0'
    runs-on: ubuntu-latest
    environment:
      name: 'Stage'
    steps:
    - uses: actions/checkout@v2
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Validate JSON
      run: jq . < stage_appsettings.json
    - name: Set Azure Web App settings
      run: |
        JSON=`cat stage_appsettings.json`
        for key in $(jq -r 'keys[]' <<< "$JSON"); do
            value=$(jq -r --arg key "$key" '.[$key]' <<< "$JSON")
            az webapp config appsettings set --name srikalistage2009 --resource-group srikali2009 --settings $key=$value
        done
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ secrets.AZURE_STAGE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_STAGE_WEBAPP_PUBLISH_PROFILE }}
        images: srikali2009.azurecr.io/myapp:${{ github.sha }}

  deploy_to_perf:
    needs: [build, test]
    if: github.ref == 'refs/heads/Release-1.0'
    runs-on: ubuntu-latest
    environment: 
      name: 'Performance'
      url: ''
    steps:
    - uses: actions/checkout@v2
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Validate JSON
      run: jq . < perf_appsettings.json
    - name: Set Azure Web App settings
      run: |
        JSON=`cat perf_appsettings.json`
        for key in $(jq -r 'keys[]' <<< "$JSON"); do
            value=$(jq -r --arg key "$key" '.[$key]' <<< "$JSON")
            az webapp config appsettings set --name srikaliperf2009 --resource-group srikali2009 --settings $key=$value
        done
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ secrets.AZURE_PERF_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_PERF_WEBAPP_PUBLISH_PROFILE }}
        images: srikali2009.azurecr.io/myapp:${{ github.sha }}
