name: Manual WebApp Config Deployment

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to checkout'
        required: true
      fileName:
        description: 'JSON file name (test, stage, perf)'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Validate JSON
        run: jq . < ${{ github.event.inputs.fileName }}_appsettings.json

      - name: Set Azure Web App settings
        run: |
          JSON=`cat ${{ github.event.inputs.fileName }}_appsettings.json`
          APP_NAME=""
          if [ "${{ github.event.inputs.fileName }}" = "test" ]
          then
            APP_NAME="srikali2009"
          elif [ "${{ github.event.inputs.fileName }}" = "stage" ]
          then
            APP_NAME="srikalistage2009"
          elif [ "${{ github.event.inputs.fileName }}" = "perf" ]
          then
            APP_NAME="srikaliperf2009"
          fi
          for key in $(jq -r 'keys[]' <<< "$JSON"); do
            value=$(jq -r --arg key "$key" '.[$key]' <<< "$JSON")
            az webapp config appsettings set --name $APP_NAME --resource-group srikali2009 --settings $key=$value
          done

      - name: Restart Azure Web App
        run: |
          APP_NAME=""
          if [ "${{ github.event.inputs.fileName }}" = "test" ]
          then
            APP_NAME="srikali2009"
          elif [ "${{ github.event.inputs.fileName }}" = "stage" ]
          then
            APP_NAME="srikalistage2009"
          elif [ "${{ github.event.inputs.fileName }}" = "perf" ]
          then
            APP_NAME="srikaliperf2009"
          fi
          az webapp restart --name $APP_NAME --resource-group srikali2009
