name: Manual Workflow

on:
  workflow_dispatch:
    inputs:
      run_id:
        description: 'Run ID'
        required: true

jobs:
  run_manual_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Print run_id
        run: echo ${{ github.event.inputs.run_id }}
